### ISSUE TITLE
Working with product systems with 1.9 openlca version

### ISSUE THREAD

**Issue by Husamalbaghdadi** [GreenDelta/openlca-python-tutorial#19]
Dear colleagues,

I updated the version of openlca to the current version (1.9) according to the upgrading of the databases. Some of the databases are not working with the old version of openlca.
Now I have a problem with creating a product system using Python. Could you please update the code within the current versions of openlca (1.9).

thank you very much for your support,
Best regards,
Husam

**Comment by msrocka** [comment]
I updated this script: https://github.com/GreenDelta/openlca-python-tutorial/blob/master/product_systems.md

I tested it with openLCA 1.10.1 which is the last stable version (note that there were some bugs in openLCA 1.9 and updating to 1.10 is recommended; also the database schema between openLCA 1.9 and 1.10 did not change so that there should be no problems to take the new version; however, a database backup is always highly recommended before running scripts or switching to a new version).
